language: python
python:
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install: pip install -r requirements-travis.txt
script: coverage run -m unittest
after_success: coveralls
notifications:
  email: false
deploy:
  provider: pypi
  user: BenWeedon
  password:
    secure: gaN8jpiXYPaiIKryoEVyElpjHidKY4bzaJHS2lf9q4pSmm/zJKqlxtP1rIBiE+fjWb4NSgvZQeHhIGWBvV8tIB0DevXWzRXTZKLHiKIJvwJP25eIJFFhnxYfJsqlEcIGqIQQqxmFZgAgEJuBE1pOsCm+fZiYmagJgDg+s4h8YEd2+FSBDmr92vZsD6MdKrXZmQ/LsBuCipLF2mWq5naRA1Nqif1/3xYkgjVliHPDlBkx6SIQo0v1oetWCxFDFPLTmNyhUMaILHtmfkU1vBnJYltEi4l6w5UbEq8D4Ol9qP6z5xkophFtpoE9MTrZkb0vKwbgaaTZ33XKx8ybXb/nBTki+A7o5X2Cch7tYzH9mvbgeeLetu/E8S5Pt3a2Jq3Xm817PJxCfn4yYr36QqpcGZDJL33ffMmaG/e5ajvG8AxCqm7RiXaiLyudKcDy6oHD+s8ctlYcN+uYzH/tkSaBtU3BVTSBpxE6+5U7XKfU6pHBUtDG6kM3/M0wIM4AZLx+hgy5zShqNU4YQ6vJYQQFymjn+FXmJK064HaTDvTFH3chpAS464NSJq2krs77s9BOqabgkKeuRZYc0ADFLM+0S7/bZUIxFeW3ckjgEuQknGawVlULi2UvRUPjRVDZF/AVrRMO/uYP4ivR9mBvLjEVMuwXMoIFzgZvIgjdu9JVqc4=
  on:
    tags: true
