language: python
python:
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
install: "pip install -r requirements-travis.txt"
script: "coverage run -m unittest"
after_success: "coveralls"

notifications:
    email: false

